"use client";

import { AlertTriangle, Building2, Calendar, MapPin } from "lucide-react";
import type { Inspection, Finding } from "@/types";

interface ReportPreviewProps {
  inspection: Inspection;
  findings: Finding[];
}

const SEVERITY_COLORS: Record<string, string> = {
  CRITICAL: "text-red-600 dark:text-red-400",
  MAJOR: "text-orange-600 dark:text-orange-400",
  MINOR: "text-yellow-600 dark:text-yellow-400",
  COSMETIC: "text-blue-600 dark:text-blue-400",
  INFO: "text-gray-500",
};

export function ReportPreview({ inspection, findings }: ReportPreviewProps) {
  const critical = findings.filter((f) => f.severity === "CRITICAL").length;
  const major = findings.filter((f) => f.severity === "MAJOR").length;
  const minor = findings.filter((f) => f.severity === "MINOR").length;
  const cosmetic = findings.filter((f) => f.severity === "COSMETIC").length;

  const topFindings = [...findings]
    .filter((f) => ["CRITICAL", "MAJOR"].includes(f.severity))
    .sort((a, b) => {
      const order = { CRITICAL: 0, MAJOR: 1, MINOR: 2, COSMETIC: 3, INFO: 4 };
      return (order[a.severity] ?? 4) - (order[b.severity] ?? 4);
    })
    .slice(0, 5);

  return (
    <div className="border-border bg-card rounded-xl border shadow-sm">
      <div className="border-border border-b px-6 py-4">
        <h2 className="text-foreground text-lg font-semibold">
          Report Preview
        </h2>
      </div>
      <div className="p-6">
        {/* Header */}
        <div className="bg-muted/50 mb-6 rounded-lg p-6">
          <div className="flex items-center gap-3">
            <div className="bg-primary flex h-12 w-12 items-center justify-center rounded-lg">
              <span className="text-primary-foreground text-lg font-bold">
                AI
              </span>
            </div>
            <div>
              <h3 className="text-foreground text-xl font-bold">
                Property Inspection Report
              </h3>
              <p className="text-muted-foreground text-sm">
                Generated by InspectAI
              </p>
            </div>
          </div>
        </div>

        {/* Property Details */}
        <div className="mb-6">
          <h4 className="text-foreground mb-3 font-semibold">
            Property Details
          </h4>
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="flex items-center gap-2 text-sm">
              <Building2 className="text-muted-foreground h-4 w-4" />
              <span className="text-muted-foreground">Property:</span>
              <span className="text-foreground font-medium">
                {inspection.propertyType
                  ?.replace(/_/g, " ")
                  .replace(/\b\w/g, (c) => c.toUpperCase())}
              </span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Calendar className="text-muted-foreground h-4 w-4" />
              <span className="text-muted-foreground">Date:</span>
              <span className="text-foreground font-medium">
                {new Date(inspection.createdAt).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </span>
            </div>
            <div className="col-span-2 flex items-center gap-2 text-sm">
              <MapPin className="text-muted-foreground h-4 w-4" />
              <span className="text-muted-foreground">Address:</span>
              <span className="text-foreground font-medium">
                {inspection.address}, {inspection.city}, {inspection.state}{" "}
                {inspection.zipCode}
              </span>
            </div>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="mb-6">
          <h4 className="text-foreground mb-3 font-semibold">
            Inspection Summary
          </h4>
          <div className="grid gap-3 sm:grid-cols-4">
            <div className="rounded-lg bg-red-500/10 p-3 text-center">
              <p className="text-2xl font-bold text-red-600 dark:text-red-400">
                {critical}
              </p>
              <p className="text-muted-foreground text-xs">Critical</p>
            </div>
            <div className="rounded-lg bg-orange-500/10 p-3 text-center">
              <p className="text-2xl font-bold text-orange-600 dark:text-orange-400">
                {major}
              </p>
              <p className="text-muted-foreground text-xs">Major</p>
            </div>
            <div className="rounded-lg bg-yellow-500/10 p-3 text-center">
              <p className="text-2xl font-bold text-yellow-600 dark:text-yellow-400">
                {minor}
              </p>
              <p className="text-muted-foreground text-xs">Minor</p>
            </div>
            <div className="rounded-lg bg-blue-500/10 p-3 text-center">
              <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                {cosmetic}
              </p>
              <p className="text-muted-foreground text-xs">Cosmetic</p>
            </div>
          </div>
        </div>

        {/* Top Findings */}
        {topFindings.length > 0 && (
          <div>
            <h4 className="text-foreground mb-3 font-semibold">
              Key Findings
            </h4>
            <div className="space-y-2">
              {topFindings.map((finding) => (
                <div
                  key={finding.id}
                  className="border-border flex items-center justify-between rounded-lg border p-3"
                >
                  <div className="flex items-center gap-3">
                    <AlertTriangle
                      className={`h-4 w-4 ${SEVERITY_COLORS[finding.severity] ?? "text-gray-500"}`}
                    />
                    <span className="text-foreground text-sm font-medium">
                      {finding.title}
                    </span>
                  </div>
                  {finding.costEstimate ? (
                    <span className="text-foreground text-sm font-semibold">
                      ${finding.costEstimate.toLocaleString()}
                    </span>
                  ) : null}
                </div>
              ))}
            </div>
          </div>
        )}

        {findings.length === 0 && (
          <p className="text-muted-foreground text-sm">
            No findings recorded for this inspection yet.
          </p>
        )}
      </div>
    </div>
  );
}
